"""Authentication commands: login, logout, status, me."""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

import click
from rich.panel import Panel

from ._common import (
    console,
    handle_command,
    require_auth,
    structured_output_options,
)

logger = logging.getLogger(__name__)


def _transfer_passphrase(env_name: str, *, confirm: bool) -> str:
    """Read a transfer passphrase without accepting it as a CLI argument."""
    value = os.environ.get(env_name)
    if value:
        return value
    return click.prompt("凭证包密码", hide_input=True, confirmation_prompt=confirm)


@click.command()
@click.option("--qrcode", is_flag=True, help="使用二维码扫码登录")
@click.option("--cookie-source", default=None, help="指定浏览器 (chrome/firefox/edge/brave/arc/safari等)")
@click.option("--cdp", is_flag=True, help="使用持久隔离 Chrome 登录并复用实时登录态")
@click.option("--cdp-port", type=click.IntRange(1, 65535), default=9222, show_default=True, help="Chrome CDP 本机端口")
@click.option("--login-timeout", type=click.IntRange(1), default=300, show_default=True, help="等待浏览器登录的秒数")
def login(qrcode: bool, cookie_source: str | None, cdp: bool, cdp_port: int, login_timeout: int) -> None:
    """扫码登录 Boss 直聘 APP"""
    from ..auth import clear_credential, verify_credential

    def _finalize_login(cred, *, from_qr: bool = False) -> None:
        # QR login cannot obtain __zp_stoken__ (generated by JS).
        # If only that cookie is missing, accept the credential with a warning
        # instead of failing the full API verification.
        if from_qr and not cred.has_required_cookies:
            missing = cred.missing_required_cookies
            if missing == ["__zp_stoken__"]:
                console.print(f"[green]✅ 登录成功！[/green] ({len(cred.cookies)} cookies)")
                console.print(
                    "[yellow]⚠️  __zp_stoken__ 缺失（该 cookie 由浏览器 JS 生成，QR 登录无法获取）。\n"
                    "   部分接口可能返回「环境异常」，建议用浏览器登录后再执行 boss login 补全。[/yellow]"
                )
                return

        authenticated, message = verify_credential(cred, force_refresh=True)
        if authenticated:
            console.print(f"[green]✅ 登录成功！[/green] ({len(cred.cookies)} cookies)")
            return
        clear_credential()
        console.print("[red]❌ 登录失败：凭证未通过实际接口校验[/red]")
        if message:
            console.print(f"[dim]{message}[/dim]")
        if not from_qr:
            console.print(
                "\n[yellow]💡 提示：浏览器运行时 Cookie 可能未写入磁盘，建议：\n"
                "   1. 关闭浏览器后重试 boss login\n"
                "   2. 或使用 boss login --qrcode 扫码登录[/yellow]"
            )
        raise SystemExit(1)

    if cdp:
        from ..cdp_login import CDPLoginUnavailable, cdp_login

        console.print("[cyan]正在打开 BOSS 专用 Chrome，请在浏览器中完成登录…[/cyan]")
        try:
            cred = cdp_login(port=cdp_port, timeout=login_timeout)
        except (CDPLoginUnavailable, RuntimeError) as exc:
            console.print(f"[red]❌ {exc}[/red]")
            raise SystemExit(1) from None
        _finalize_login(cred)
        console.print("[dim]专用 Chrome 将保持运行，以持续维护登录态。[/dim]")
    elif qrcode:
        # Prefer browser-assisted login (captures __zp_stoken__ via JS)
        # Fallback to HTTP-only QR flow when camoufox is unavailable
        try:
            from ..browser_login import browser_qr_login, BrowserLoginUnavailable
            try:
                cred = browser_qr_login()
                _finalize_login(cred, from_qr=True)
                return
            except BrowserLoginUnavailable as e:
                console.print(
                    f"[yellow]⚠️  浏览器辅助登录不可用: {e}\n"
                    "   安装方式: pip install 'kabi-boss-cli[browser]' && python -m camoufox fetch\n"
                    "   回退到 HTTP 扫码登录...[/yellow]\n"
                )
        except ImportError:
            pass

        # Fallback: HTTP-only QR login
        from ..auth import qr_login
        import asyncio
        try:
            cred = asyncio.run(qr_login())
        except RuntimeError as e:
            console.print(f"[red]❌ {e}[/red]")
            raise SystemExit(1) from None
        _finalize_login(cred, from_qr=True)
    else:
        from ..auth import extract_browser_credential, _diagnose_extraction_issues
        # Try browser cookies first
        cred, diagnostics = extract_browser_credential(cookie_source=cookie_source)
        if cred:
            _finalize_login(cred)
        else:
            # Show diagnostics hint if available
            hint = _diagnose_extraction_issues(diagnostics)
            if hint:
                console.print("[yellow]⚠️  Cookie 提取诊断:[/yellow]")
                for line in hint.splitlines():
                    console.print(f"  [dim]{line}[/dim]")
                console.print()

            # Fallback to QR login
            console.print("[yellow]未找到浏览器 Cookie，尝试二维码登录...[/yellow]")
            console.print("[dim]💡 也可以手动设置 BOSS_COOKIES 环境变量来注入 cookie[/dim]")
            try:
                from ..browser_login import browser_qr_login, BrowserLoginUnavailable
                try:
                    cred = browser_qr_login()
                    _finalize_login(cred, from_qr=True)
                    return
                except BrowserLoginUnavailable:
                    pass
            except ImportError:
                pass

            from ..auth import qr_login
            import asyncio
            try:
                cred = asyncio.run(qr_login())
            except RuntimeError as e:
                console.print(f"[red]❌ {e}[/red]")
                raise SystemExit(1) from None
            _finalize_login(cred, from_qr=True)


@click.command()
def logout() -> None:
    """清除已保存的登录凭证"""
    from ..auth import clear_credential
    clear_credential()
    console.print("[green]✅ 已退出登录[/green]")


@click.command("config-export")
@click.argument("output", type=click.Path(path_type=Path, dir_okay=False))
@click.option("--passphrase-env", default="BOSS_CREDENTIAL_PASSPHRASE", show_default=True, help="读取密码的环境变量名")
@click.option("--refresh/--no-refresh", default=True, show_default=True, help="导出前刷新浏览器实时登录态")
@click.option("--force", is_flag=True, help="覆盖已存在的导出文件")
def config_export(output: Path, passphrase_env: str, refresh: bool, force: bool) -> None:
    """一键导出登录态和插件配置为加密完整配置包。"""
    from ..auth import get_credential, refresh_credential
    from ..config_transfer import collect_portable_settings, export_config_file
    from ..credential_transfer import CredentialTransferError

    credential = None
    if refresh:
        credential, _ = refresh_credential()
    if credential is None:
        credential = get_credential()
    if credential is None:
        console.print("[red]❌ 没有可导出的登录态，请先执行 boss login[/red]")
        raise SystemExit(1)

    passphrase = _transfer_passphrase(passphrase_env, confirm=True)
    try:
        settings = collect_portable_settings()
        export_config_file(output, credential, settings, passphrase, overwrite=force)
    except CredentialTransferError as exc:
        console.print(f"[red]❌ 导出失败: {exc}[/red]")
        raise SystemExit(1) from None
    console.print(f"[green]✅ 已导出加密完整配置包: {output.expanduser()}[/green]")
    console.print(f"[dim]包含登录态和 {len(settings)} 项可移植配置；不包含缓存、日志或浏览器 Profile。[/dim]")
    console.print("[yellow]请通过安全通道传输文件，并与密码分开保存。[/yellow]")


@click.command("config-import")
@click.argument("input_file", type=click.Path(path_type=Path, exists=True, dir_okay=False, readable=True))
@click.option("--passphrase-env", default="BOSS_CREDENTIAL_PASSPHRASE", show_default=True, help="读取密码的环境变量名")
@click.option("--verify", is_flag=True, help="保存后调用 BOSS 接口验证，失败则恢复原凭证")
@click.option("--force", is_flag=True, help="无需确认即可覆盖现有登录态和插件配置")
def config_import(input_file: Path, passphrase_env: str, verify: bool, force: bool) -> None:
    """一键导入加密配置包；兼容旧版仅凭证包。"""
    from ..auth import clear_credential, load_credential, save_credential, verify_credential
    from ..config_transfer import (
        CONFIG_PACKAGE_FORMAT,
        import_config_file,
        read_package_format,
        write_portable_settings,
    )
    from ..constants import PLUGIN_ENV_FILE
    from ..credential_transfer import CredentialTransferError, import_credential_file
    from ..io_utils import atomic_write_private

    previous = load_credential()
    previous_env = PLUGIN_ENV_FILE.read_text(encoding="utf-8") if PLUGIN_ENV_FILE.exists() else None
    if (previous is not None or previous_env is not None) and not force:
        click.confirm("本地已有登录态或插件配置，是否覆盖？", abort=True)

    passphrase = _transfer_passphrase(passphrase_env, confirm=False)
    try:
        package_format = read_package_format(input_file)
        if package_format == CONFIG_PACKAGE_FORMAT:
            bundle = import_config_file(input_file, passphrase)
            credential = bundle.credential
            settings = bundle.settings
        else:
            credential = import_credential_file(input_file, passphrase)
            settings = None
    except CredentialTransferError as exc:
        console.print(f"[red]❌ 导入失败: {exc}[/red]")
        raise SystemExit(1) from None

    try:
        save_credential(credential)
        if settings is not None:
            write_portable_settings(settings, PLUGIN_ENV_FILE)
        if verify:
            authenticated, reason = verify_credential(credential, force_refresh=True)
            if not authenticated:
                raise CredentialTransferError(reason or "导入登录态未通过在线验证")
    except Exception as exc:
        try:
            if previous is not None:
                save_credential(previous)
            else:
                clear_credential()
            if previous_env is not None:
                atomic_write_private(PLUGIN_ENV_FILE, previous_env)
            else:
                PLUGIN_ENV_FILE.unlink(missing_ok=True)
        except OSError:
            logger.exception("Failed to roll back imported configuration")
        console.print("[red]❌ 导入配置失败，已恢复原登录态和插件配置[/red]")
        console.print(f"[dim]{exc}[/dim]")
        raise SystemExit(1) from None

    if settings is None:
        console.print(f"[green]✅ 已导入旧版登录态[/green] ({len(credential.cookies)} cookies)")
    else:
        console.print(
            f"[green]✅ 已导入完整配置[/green] "
            f"({len(credential.cookies)} cookies, {len(settings)} 项插件配置)"
        )
        console.print("[yellow]请重启 boss-plugin 或容器，使新配置全部生效。[/yellow]")
    if not verify:
        console.print("[dim]尚未在线验证，可运行 boss status 或导入时添加 --verify。[/dim]")


# Backward-compatible command object aliases. New documentation should use
# config-export/config-import, while existing scripts keep working unchanged.
credential_export = config_export
credential_import = config_import


@click.command()
@structured_output_options
def status(as_json: bool, as_yaml: bool) -> None:
    """查看当前登录状态"""
    from ..auth import get_credential, verify_credential_details
    cred = get_credential()
    if cred:
        cookie_names = sorted(cred.cookies.keys())
        health = verify_credential_details(cred)
        authenticated = health["authenticated"]
        message = health.get("reason")
        data = {
            "credential_present": True,
            "cookie_count": len(cred.cookies),
            "cookies": cookie_names,
            **health,
        }
        if as_json:
            click.echo(json.dumps(data, indent=2, ensure_ascii=False))
        elif as_yaml:
            try:
                import yaml
                click.echo(yaml.dump(data, allow_unicode=True))
            except ImportError:
                click.echo(json.dumps(data, indent=2, ensure_ascii=False))
        else:
            n = len(cred.cookies)
            keys = ", ".join(cookie_names[:5])
            extra = f" (+{n - 5} more)" if n > 5 else ""
            if authenticated:
                console.print(f"[green]✅ 已登录[/green] ({n} cookies)")
                console.print(f"  [dim]{keys}{extra}[/dim]")
            else:
                console.print(f"[yellow]⚠️  本地存在凭证，但登录态无效[/yellow] ({n} cookies)")
                console.print(f"  [dim]{keys}{extra}[/dim]")
            console.print(
                "  [dim]"
                f"search={'ok' if health['search_authenticated'] else 'fail'} · "
                f"recommend={'ok' if health['recommend_authenticated'] else 'fail'}"
                "[/dim]"
            )
            if message:
                console.print(f"  [dim]{message}[/dim]")
    else:
        if as_json:
            click.echo(json.dumps({"authenticated": False, "credential_present": False}))
        elif as_yaml:
            data = {"authenticated": False, "credential_present": False}
            try:
                import yaml
                click.echo(yaml.dump(data, allow_unicode=True))
            except ImportError:
                click.echo(json.dumps(data, indent=2, ensure_ascii=False))
        else:
            console.print("[yellow]⚠️  未登录[/yellow]，使用 [bold]boss login[/bold] 扫码登录")


@click.command()
@structured_output_options
def me(as_json: bool, as_yaml: bool) -> None:
    """查看个人资料和求职期望"""
    cred = require_auth()

    def _render(info: dict) -> None:
        name = info.get("name", info.get("nickName", "-"))
        age = info.get("age", "-")
        degree = info.get("degreeCategory", "-")
        account = info.get("account", "-")
        gender = "男" if info.get("gender") == 1 else "女" if info.get("gender") == 2 else "-"

        panel = Panel(
            f"[bold]{name}[/bold]  {gender}  {age}\n"
            f"学历: {degree}\n"
            f"账号: {account}",
            title="👤 个人资料",
            border_style="cyan",
        )
        console.print(panel)

    handle_command(
        cred,
        action=lambda c: c.get_resume_baseinfo(),
        render=_render,
        as_json=as_json,
        as_yaml=as_yaml,
    )
